# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    file_upload_directory: '%kernel.project_dir%/public/uploads-real/'
    asset_directory: '%kernel.project_dir%/public/build/'
    mailer_transports:
        main: '%env(MAILER_DSN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $assetDir: '%asset_directory%'
            $projectDir: '%kernel.project_dir%/'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Service\MailSender:
        arguments:
            $uploadDirectory: '%file_upload_directory%'
            $assetDirectory: '%asset_directory%'
            $transports: '%mailer_transports%'

    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: [ "@knp_menu.factory" , '@security.helper', '@knp_menu.matcher','system/main.html.twig' ]
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main } # The alias is what is used to retrieve the menu

    App\EventListener\DoctrineSchemaListener:
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: doctrine.event_subscriber }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
