#!/bin/bash

echo 'Updating development environment...'

docker-compose build
docker-compose down && sleep 3 && docker-compose up -d
docker exec -t rotary_php composer install --ignore-platform-reqs -n
docker exec -u root -t rotary_php yarn install
docker exec -it rotary_php bin/console doct:migr:migr --no-interaction
docker exec -u root -t rotary_php yarn encore dev
